org: fortizabril
app: tejodoro
service: tejodoro-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
