org: fortizabril
app: tejodoro
service: tejodoro-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  getPomodoro:
    handler: handler.getPomodoro
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
