name: API

on:
  push:
    paths:
    - 'api/**'

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Npm install
        run: npm ci --no-audit

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: endsWith(github.ref, '/main')
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: ./api
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tejodoro"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
