name: Web App

on:
  push:
    paths:
    - 'webapp/**'

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Npm install
        run: npm ci --no-audit

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
            appdir: ./webapp
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "tejodoro-web-app"
            heroku_email: ${{secrets.HEROKU_EMAIL}}