name: Web App

on:
  push:
    paths:
    - 'webapp/**'

defaults:
  run:
    working-directory: ./webapp

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Npm install
        run: npm ci --no-audit

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [16.x]
    if: endsWith(github.ref, '/main')
    steps:
      - uses: actions/checkout@v3
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
