name: Web App

on: [push]

jobs:
 
  build:
    runs-on: ubuntu-latest`
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        working-directory: ./webapp
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "tejodoro-web-app"
            heroku_email: "ronnyancorini@gmail.com"